export const SPACE_CONFIGS = [
  // Start with a small spiral
  { id: 1, type: 'normal' as const },
  { id: 2, type: 'normal' as const },
  { id: 3, type: 'normal' as const },
  { id: 4, type: 'normal' as const },
  { id: 5, type: 'normal' as const },
  { id: 6, type: 'normal' as const },
  { id: 7, type: 'normal' as const },
  { id: 8, type: 'normal' as const },
  { id: 9, type: 'normal' as const },
  { id: 10, type: 'prize' as const, description: 'Small Prize!', funEffect: 'sparkle' },
  { id: 11, type: 'normal' as const },
  { id: 12, type: 'normal' as const },
  { id: 13, type: 'normal' as const },
  { id: 14, type: 'prize' as const, description: 'Medium Prize!', funEffect: 'sparkle' },
  { id: 15, type: 'normal' as const },
  { id: 16, type: 'normal' as const },
  { id: 17, type: 'normal' as const },
  { id: 18, type: 'normal' as const },
  { id: 19, type: 'normal' as const },
  { id: 20, type: 'prize' as const, description: 'Medium Prize!', funEffect: 'sparkle' },
  { id: 21, type: 'normal' as const },
  { id: 22, type: 'normal' as const },
  { id: 23, type: 'normal' as const },
  { id: 24, type: 'prize' as const, description: 'Large Prize!', funEffect: 'sparkle' },
  { id: 25, type: 'normal' as const },
  { id: 26, type: 'normal' as const },
  { id: 27, type: 'normal' as const },
  { id: 28, type: 'normal' as const },
  { id: 29, type: 'normal' as const },
  { id: 30, type: 'prize' as const, description: 'Small Prize!', funEffect: 'sparkle' },
  { id: 31, type: 'normal' as const },
  { id: 32, type: 'normal' as const },
  { id: 33, type: 'normal' as const },
  { id: 34, type: 'normal' as const },
  { id: 35, type: 'normal' as const },
  { id: 36, type: 'prize' as const, description: 'Small Prize!', funEffect: 'sparkle' },
  { id: 37, type: 'normal' as const },
  { id: 38, type: 'normal' as const },
  { id: 39, type: 'normal' as const },
  { id: 40, type: 'prize' as const, description: 'Large Prize!', funEffect: 'sparkle' },
  { id: 41, type: 'normal' as const },
  { id: 42, type: 'normal' as const },
  { id: 43, type: 'normal' as const },
  { id: 44, type: 'normal' as const },
  { id: 45, type: 'prize' as const, description: 'Medium Prize!', funEffect: 'sparkle' },
  { id: 46, type: 'normal' as const },
  { id: 47, type: 'normal' as const },
  { id: 48, type: 'normal' as const },
  { id: 49, type: 'normal' as const },
  { id: 50, type: 'prize' as const, description: 'Random Prize!', funEffect: 'sparkle' },
  { id: 51, type: 'normal' as const },
  { id: 52, type: 'normal' as const },
  { id: 53, type: 'normal' as const },
  { id: 54, type: 'prize' as const, description: 'Small Prize!', funEffect: 'sparkle' },
  { id: 55, type: 'normal' as const },
  { id: 56, type: 'normal' as const },
  { id: 57,type: 'prize' as const, description: 'Large Prize!', funEffect: 'sparkle' },
  { id: 58, type: 'normal' as const },
  { id: 59, type: 'normal' as const },
  { id: 60, type: 'prize' as const, description: 'Small Prize!', funEffect: 'sparkle' },
  { id: 61, type: 'normal' as const },
  { id: 62, type: 'normal' as const },
  { id: 63, type: 'normal' as const },
  { id: 64, type: 'normal' as const },
  { id: 65, type: 'prize' as const, description: 'Large Prize!', funEffect: 'sparkle' },
  { id: 66, type: 'normal' as const },
  { id: 67, type: 'normal' as const },
  { id: 68, type: 'normal' as const },
  { id: 69, type: 'normal' as const },
  { id: 70, type: 'prize' as const, description: 'Medium Prize!', funEffect: 'sparkle' },
  { id: 71, type: 'normal' as const },
  { id: 72, type: 'normal' as const },
  { id: 73, type: 'normal' as const },
  { id: 74, type: 'normal' as const },
  { id: 75, type: 'prize' as const, description: 'Small Prize!', funEffect: 'sparkle' },
  { id: 76, type: 'normal' as const },
  { id: 77, type: 'normal' as const },
  { id: 78, type: 'normal' as const },
  { id: 79, type: 'normal' as const },
  { id: 80, type: 'prize' as const, description: 'Large Prize!', funEffect: 'sparkle' },
  { id: 81, type: 'normal' as const },
  { id: 82, type: 'normal' as const },
  { id: 83, type: 'normal' as const },
  { id: 84, type: 'normal' as const },
  { id: 85, type: 'prize' as const, description: 'Random Prize!', funEffect: 'sparkle' },
  { id: 86, type: 'normal' as const },
  { id: 87, type: 'normal' as const },
  { id: 88, type: 'normal' as const },
  { id: 89, type: 'normal' as const },
  { id: 90, type: 'prize' as const, description: 'Small Prize!', funEffect: 'sparkle' },
  { id: 91, type: 'normal' as const },
  { id: 92, type: 'normal' as const },
  { id: 93, type: 'normal' as const },
  { id: 94, type: 'normal' as const },
  { id: 95, type: 'prize' as const, description: 'Medium Prize!', funEffect: 'sparkle' },
  { id: 96, type: 'normal' as const },
  { id: 97, type: 'normal' as const },
  { id: 98, type: 'normal' as const },
  { id: 99, type: 'normal' as const },
  { id: 100, type: 'prize' as const, description: 'Awardco Grand Prize!', funEffect: 'sparkle' }
]; 
